#!/bin/bash
ROOT=.
MIRROR_ROOT=$ROOT/mirror
check_absolute() {
	[[ $1 =~ ^/ ]]
}
CP () {
	local DIR=$(dirname $1)
	[[ -d $MIRROR_ROOT/$DIR ]] || mkdir -p $MIRROR_ROOT/$DIR
	cp -p $1 $MIRROR_ROOT/$DIR
}
init () {
	git init
	mkdir mirror
}
add () {
	local file=$1
	check_absolute $file || { echo "Path must be absolute"; return 1; }
	[[ -f $file ]] || { echo "No such file"; return 2; }
	[[ -f $MIRROR_ROOT/$file ]] && { echo "file already added";return 3; }
	CP $file
	git add $MIRROR_ROOT/$file
}
update () {
	rsync -av --files-from=<(git ls-files|sed "s/^mirror//") / $MIRROR_ROOT
}
rm () {
	local file=$1
	check_absolute $file || { echo "Path must be absolute"; return 1; }
	[[ -f $MIRROR_ROOT/$file ]] || { echo "file not added"; return 2; }
	git rm -f $MIRROR_ROOT/$file
}
commit () {
	git commit -a
}
$1 $2
